name: twenty

services:
  server:
    container_name: app-twentycrm-server
    image: twentycrm/twenty:v1.15
    ports:
      - "3023:3000"
    environment:
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: http://192.168.1.46:3023
      FRONT_BASE_URL: http://192.168.1.46:3023
      REDIS_URL: redis://redis:6379
      APP_SECRET: replace_me_with_a_random_string
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: /app/.local-storage
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    container_name: app-twentycrm-db
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: unless-stopped

  redis:
    container_name: app-twentycrm-redis
    image: redis
    restart: unless-stopped