name: twenty

services:
  server:
    container_name: app-twentycrm-server
    image: twentycrm/twenty:latest
    ports:
      - "3030:3000"
    environment:
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: http://ryvie.local:3030
      REDIS_URL: redis://redis:6379
      APP_SECRET: replace_me_with_a_random_string
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    container_name: app-twentycrm-db
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: unless-stopped

  redis:
    image: redis
    restart: always