name: twenty

services:
  server:
    container_name: app-twentycrm-server
    image: twentycrm/twenty:v1.15
    ports:
      - "${PORT}:3000"
    environment:
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/default
      SERVER_URL: http://${DOMAIN}:${PORT}
      FRONT_BASE_URL: http://${DOMAIN}:${PORT}
      REDIS_URL: redis://redis:6379
      APP_SECRET: ${APP_SECRET}
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: /app/.local-storage
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    container_name: app-twentycrm-db
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
    restart: unless-stopped

  redis:
    container_name: app-twentycrm-redis
    image: redis
    restart: unless-stopped