services:
  fossflow: 
    container_name: app-fossflow
    image: stnsmith/fossflow@sha256:3afa469d07b802c97fe9d8556a621baa192e4e785087a8a4bce755f457505cdc
    pull_policy: always 
    ports:
      - 3012:80
    environment: 
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=${ENABLE_SERVER_STORAGE:-true}
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=${ENABLE_GIT_BACKUP:-false}
    volumes: 
      - ./diagrams:/data/diagrams
    restart: unless-stopped 
    