services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    container_name: app-docuseal
    ports:
      - "3020:3000"
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
      - DISABLE_REDIS=true
      - SECRET_KEY_BASE=changez_cette_cle_par_une_longue_chaine_aleatoire_de_128_caracteres_minimum_1234567890abcdef
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: app-docuseal-postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: app-docuseal-caddy
    command: caddy reverse-proxy --from ryvietest.local --to app:3000
    ports:
      - "80:80"
      - "445:443"
      - "445:443/udp"
    restart: unless-stopped