services:
  bitwarden:
    container_name: app-bitwarden-server
    depends_on:
      - db
    env_file:
      - .env
    image: ghcr.io/bitwarden/self-host:latest
    restart: unless-stopped
    ports:
      - "3018:8080"
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden
    networks:
      - bitwarden-network

  db:
    container_name: app-bitwarden-db
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    networks:
      - bitwarden-network

networks:
  bitwarden-network:

volumes:
  bitwarden:
  logs:
  data: