services:
  vaultwarden:
    container_name: app-bitwarden-server
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    environment:
      DOMAIN: "https://bitwarden.ryvietest.local"
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true