services:
  vaultwarden:
    container_name: app-bitwarden-server
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "3018:80"
    volumes:
      - ./vw-data:/data
    environment:
      DOMAIN: "http://localhost:3018"
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
    networks:
      - bitwarden-network

networks:
  bitwarden-network: