services:
  mealie:
    container_name: app-mealie
    image: hkotel/mealie:v3.9.2
    volumes:
      - ./mealie-data:/app/data/
    ports:
      - 9091:9000
    environment:
      TZ: Europe/Paris
    restart: unless-stopped
    
volumes:
  mealie-data:
   