services:
  app_proxy:
    image: nginx:alpine
    environment:
      APP_HOST: n8n_server_1
      APP_PORT: 5678
      PROXY_AUTH_WHITELIST: "/webhook-test/*,/webhook/*"
    container_name: app-n8n-proxy
    restart: unless-stopped

  server:
    image: n8nio/n8n:1.117.3@sha256:90bf64ec238b88908389694b5ace00e5c17ea5d4a0af812dd266d7cfcd40984f
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    container_name: app-n8n-server
    user: "1000:1000"
    environment:
      - N8N_HOST=${DEVICE_DOMAIN_NAME}
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    restart: unless-stopped