version: "3.8"

services:
  # Ce service r√©pare les permissions automatiquement avant le lancement de n8n
  init-permissions:
    image: busybox
    user: root
    volumes:
      - ./data:/home/node/.n8n
    command: chown -R 1000:1000 /home/node/.n8n 

  n8n:
    image: n8nio/n8n:2.3.2
    container_name: app-n8n
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      init-permissions:
        condition: service_completed_successfully
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./data:/home/node/.n8n
