services:
  pihole:
    container_name: app-pihole
    image: pihole/pihole:latest
    ports:
      - "3021:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Paris'
      FTLCONF_webserver_api_password: 'ryvie'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './data/etc-pihole:/etc/pihole'
    restart: unless-stopped