version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ce:18.5.1-ce.0@sha256:6db4caefb0597c966065f4c3307b60aa00d13559bbe9b0c3b17bc32f0d239ab1
    restart: unless-stopped
    hostname: '${DEVICE_DOMAIN_NAME}:8929'
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      PUID: 1000
      PGID: 1000
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = '${APP_PASSWORD}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        nginx['listen_port'] = 8929
        nginx['listen_https'] = false
    ports:
      - '2424:22'
    volumes:
      - ./data/config:/etc/gitlab
      - ./data/logs:/var/log/gitlab
      - ./data/data:/var/opt/gitlab
    shm_size: '256m'
    container_name: app-gitlab