services:
  gitlab:
    image: gitlab/gitlab-ce:18.5.1-ce.0@sha256:6db4caefb0597c966065f4c3307b60aa00d13559bbe9b0c3b17bc32f0d239ab1
    container_name: app-gitlab
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'http://gitlab.example.com:8929'
    #    gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '2024:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'