services:
  node:
    image: "julescloud/rdrop-node:v0.0.1"
    container_name: app-rdrop-node
    restart: unless-stopped

  nginx:
    image: "julescloud/rdrop-nginx:v0.0.1"
    ports:
      - "8080:80"
    env_file: ${PWD}/docker/fqdn.env
    entrypoint: /mnt/openssl/create.sh
    command: ["nginx", "-g", "daemon off;"]
    container_name: app-rdrop-nginx
    restart: unless-stopped
