version: "3.7"

services:
  postgres:
    container_name: app-linkwarden-postgres
    image: postgres:16-alpine@sha256:0366402213df5db03c47ff80bcc697e92c8be0c213d03c941df1fc42d1ba9560
    environment:
      - POSTGRES_PASSWORD=linkwarden
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: app-linkwarden-app
    image: ghcr.io/linkwarden/linkwarden:v2.13.1@sha256:54271afa4fc34107f98d9ba580e320e3bd5b3e02339f7d68947d01a375ea7bb3
    ports:
      - "3028:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:linkwarden@postgres:5432/postgres
      - NEXTAUTH_URL=http://ryvie.local:3028/api/v1/auth
      - NEXTAUTH_SECRET=linkwarden
    restart: unless-stopped
    volumes:
      - ./data/app:/data/data
    depends_on:
      postgres:
        condition: service_healthy
        