services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: app-jellyfin
    user: "1000:1000"
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/cache:/cache
      - ${APP_DATA_DIR}/media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://${DEVICE_DOMAIN_NAME}
    extra_hosts:
      - 'host.docker.internal:host-gateway'