version: '3.9'

services:
  web:
    image: ghcr.io/toeverything/affine:0.25.1
    container_name: affine_web
    restart: unless-stopped
    ports:
      - "3015:3010"
    environment:
      AFFINE_CONFIG_PATH: /root/.affine/config
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgres://affine:affine@db:5432/affine
      NODE_ENV: production
    volumes:
      - ./data/config:/root/.affine/config
      - ./data/storage/blob:/root/.affine/storage
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - affine-network

  migration:
    image: ghcr.io/toeverything/affine:0.25.1
    container_name: affine_migration
    restart: "no"
    command: ["sh", "-c", "node ./scripts/self-host-predeploy"]
    environment:
      AFFINE_CONFIG_PATH: /root/.affine/config
      REDIS_SERVER_HOST: redis
      DATABASE_URL: postgres://affine:affine@db:5432/affine
      NODE_ENV: production
    volumes:
      - ./data/config:/root/.affine/config
      - ./data/storage/blob:/root/.affine/storage
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - affine-network

  redis:
    image: redis:7.2.4
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ./data/storage/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - affine-network

  db:
    image: postgres:16.2
    container_name: affine_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/storage/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affine"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - affine-network

networks:
  affine-network: